In [1]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np

In [2]:
X_train = np.array([[ 2., 0.,  1.],
                    [ 4.,  0.,  0.],
                    [ 0.,  2., -2.],
                    [ 2.,  2., -1.]])

In [3]:
#创建转化模型、训练、数据处理
scaler = MinMaxScaler(feature_range=(0,1))
scaler = scaler.fit(X_train)
result = scaler.transform(X_train)

In [4]:
#数据最小值
scaler.data_min_

array([ 0.,  0., -2.])

In [5]:
#数据最大值
scaler.data_max_

array([4., 2., 1.])

In [6]:
#数据范围
scaler.data_range_

array([4., 2., 3.])

In [7]:
#数据处理结果
result

array([[0.5       , 0.        , 1.        ],
       [1.        , 0.        , 0.66666667],
       [0.        , 1.        , 0.        ],
       [0.5       , 1.        , 0.33333333]])