In [1]:
from sklearn.preprocessing import StandardScaler
import numpy as np

In [2]:
X_train = np.array([[ 2., 0.,  1.],
                    [ 4.,  0.,  0.],
                    [ 0.,  2., -2.],
                    [ 2.,  2., -1.]])

In [3]:
scaler = StandardScaler()
scaler = scaler.fit(X_train)
result = scaler.transform(X_train)

In [4]:
scaler.mean_

array([ 2. ,  1. , -0.5])

In [5]:
scaler.scale_

array([1.41421356, 1.        , 1.11803399])

In [6]:
scaler.var_

array([2.  , 1.  , 1.25])

In [7]:
result

array([[ 0.        , -1.        ,  1.34164079],
       [ 1.41421356, -1.        ,  0.4472136 ],
       [-1.41421356,  1.        , -1.34164079],
       [ 0.        ,  1.        , -0.4472136 ]])